### ISSUE TITLE
it's wrong to describe both endpoints ip are pod ips?

### ISSUE THREAD

**Issue by jeffcai** [zhongfox/multicluster-demo#1]
this's a great article, but have a question (which actually confuse me) regarding the statements below:

>172.25.0.26:7000是广州集群的 recommend v1 pod, 而119.28.109.157:443对应的是新加坡集群 recommend v2 pod. 这些服务实例对业务代码来说是透明的, 访问 recommend 服务可以随机路由到任一集群。

it's wrong to say the 119.28.109.157:443 ip is pod ip, instead it should be sg cluster ingress gateway ip?
>119.28.109.157:443对应的是新加坡集群 recommend v2 pod 

Thanks,

**Comment by zhongfox** [comment]
你的说法是正确的，原文表达不准确：
原文并没有说 119.28.109.157:443 是pod ip, 当前语境里 119.28.109.157:443  代表了一个recommend的 endpoint。
我调整下表达： 
而`119.28.109.157:443` (新加坡 ingress gateway)在这里对应的是新加坡集群 recommend v2 的服务实例
